name: Decorize

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  'CI / CD':
    env:
      CI: true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Changelog
        run: node common/scripts/install-run-rush.js change -v
      - name: Install
        run: node common/scripts/install-run-rush.js update
      - name: Build
        run: node common/scripts/install-run-rush.js build
      - name: Lint
        run: node common/scripts/install-run-rush.js lint
      - name: Test
        run: node common/scripts/install-run-rush.js test
      - name: Report
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: >-
            ./package/core/coverage/lcov.info,
            ./package/cache/coverage/lcov.info,
            ./package/bind/coverage/lcov.info
